---
- hosts: prod_node
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: finalapp
        image: "{{ docker_image }}"
        state: started
        restart_policy: always