---
- hosts: build_node
  become: yes
  tasks:
    - name: Remove apt lock files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend

    - name: Reconfigure dpkg
      command: dpkg --configure -a
      ignore_errors: yes

    - name: Clean apt cache
      command: apt-get clean
      ignore_errors: yes

    - name: Check if apt-get update fails
      command: apt-get update
      register: apt_update
      ignore_errors: yes

    - name: Print apt-get update output
      debug:
        msg: "{{ apt_update.stdout }}"
      when: apt_update.failed

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: true
