---
- hosts: build_node
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "aamitv/myapp:latest"
        source: pull

    - name: Stop and remove existing container if it exists
      docker_container:
        name: finalapp
        state: absent
      ignore_errors: yes

    - name: Run Docker container
      docker_container:
        name: finalapp
        image: "aamitv/myapp:latest"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"  