---
- hosts: build_node
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone the repository
      git:
        repo: 'https://github.com/AAM-ITV/project12.git'
        dest: /home/jenkins/project

    - name: Build Docker image
      shell: |
         docker-compose up -d

    - name: Login to Docker Hub
      shell: |
        echo "Createistrue12" | docker login -u "aamitv" --password-stdin
      no_log: true

    - name: Push Docker image to Docker Hub
      shell: |
        docker push aamitv/app:latest
